version: '3.8'

services:
  # Primer conjunto de servicios (IoT) - Con RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management  # Versión actualizada
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: iotuser
      RABBITMQ_DEFAULT_PASS: iotpassword
    ports:
      - "5672:5672"  # Puerto AMQP
      - "15672:15672"  # Puerto de la interfaz web
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - iot-network

  db-iot:
    image: postgres:16
    environment:
      POSTGRES_DB: iotbase
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: userpassword2
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-iot:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user2 -d iotbase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - iot-network

  pgadmin-iot:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin2@admin2.com
      PGADMIN_DEFAULT_PASSWORD: admin2
    ports:
      - "8081:80"
    depends_on:
      db-iot:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - iot-network

  sensor-api:
    build:
      context: ./IOT/sensor-api
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-iot:5432/iotbase
      QUARKUS_DATASOURCE_USERNAME: user2
      QUARKUS_DATASOURCE_PASSWORD: userpassword2
      QUARKUS_RABBITMQ_HOST: rabbitmq  # Conexión al servicio RabbitMQ
      QUARKUS_RABBITMQ_PORT: 5672
      QUARKUS_RABBITMQ_USERNAME: iotuser
      QUARKUS_RABBITMQ_PASSWORD: iotpassword
    depends_on:
      db-iot:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - iot-network

  # Segundo conjunto de servicios (Agricultura) - Sin RabbitMQ
  db-agri:
    image: postgres:16
    environment:
      POSTGRES_DB: agriculbase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-agri:/var/lib/postgresql/data
    networks:
      - agri-network

  pgadmin-agri:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db-agri
    networks:
      - agri-network

  api-agri:
    build:
      context: ./Productos/ProductsService.API
      dockerfile: Docker/Dockerfile
    ports:
      - "5206:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db-agri;Port=5432;Database=agriculbase;Username=user;Password=userpassword"
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - db-agri
    networks:
      - agri-network

volumes:
  postgres-data-iot:
  postgres-data-agri:

networks:
  iot-network:
    driver: bridge
  agri-network:
    driver: bridge